services:
  - type: web
    name: smartnutri-backend
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: cd backend && gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
